name: oratorz
description: An All-In-One MUN Aid.

publish_to: "none"
version: 1.0.0+4

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  firebase_core: ^2.4.1
  firebase_analytics: ^10.1.0
  scrollable_positioned_list: ^0.3.5
  percent_indicator: ^4.2.2
  flutter_dropzone: ^3.0.5
  dropdown_search: ^5.0.5
  universal_html: ^2.0.8
  url_launcher: ^6.1.7
  google_fonts: ^3.0.1
  get_storage: ^2.0.3
  file_picker: ^5.2.4
  go_router: ^6.0.0
  excel: ^2.0.1
  intl: ^0.18.0
  http: ^0.13.5
  get: ^4.6.5

dev_dependencies:
  flutter_lints: ^2.0.1

  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
