name: oratorz
description: An All-In-One MUN Aid.

publish_to: "none"
version: 1.0.0+4

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  shared_preferences: ^2.0.15
  percent_indicator: ^4.2.2
  universal_html: ^2.0.8
  url_launcher: ^6.1.7
  google_fonts: ^3.0.1
  go_router: ^6.0.0
  intl: ^0.18.0
  http: ^0.13.5
  get: ^4.6.5

dev_dependencies:
  flutter_lints: ^2.0.1

  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
