// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          "DefaultFirebaseOptions have not been configured for android - "
          "you can reconfigure this by running the FlutterFire CLI again.",
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          "DefaultFirebaseOptions have not been configured for ios - "
          "you can reconfigure this by running the FlutterFire CLI again.",
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          "DefaultFirebaseOptions have not been configured for macos - "
          "you can reconfigure this by running the FlutterFire CLI again.",
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          "DefaultFirebaseOptions have not been configured for windows - "
          "you can reconfigure this by running the FlutterFire CLI again.",
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          "DefaultFirebaseOptions have not been configured for linux - "
          "you can reconfigure this by running the FlutterFire CLI again.",
        );
      default:
        throw UnsupportedError(
          "DefaultFirebaseOptions are not supported for this platform.",
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDuLF8uzcD51hS9fiJKYzZHX5uWFvBuVmg",
    appId: "1:349136834707:web:3d6d0d62fca250d6cebd66",
    messagingSenderId: "349136834707",
    projectId: "oratorz37",
    authDomain: "oratorz37.firebaseapp.com",
    storageBucket: "oratorz37.appspot.com",
    measurementId: "G-Q6TCZ1SW7D",
  );
}
