// ignore_for_file: non_constant_identifier_names

final Map<String, String> COUNTRIES = {
  "AND": "Andorra",
  "ARE": "United Arab Emirates",
  "AFG": "Afghanistan",
  "ATG": "Antigua and Barbuda",
  "ALB": "Albania",
  "ARM": "Armenia",
  "AGO": "Angola",
  "ARG": "Argentina",
  "AUT": "Austria",
  "AUS": "Australia",
  "AZE": "Azerbaijan",
  "BIH": "Bosnia and Herzegovina",
  "BRB": "Barbados",
  "BGD": "Bangladesh",
  "BEL": "Belgium",
  "BFA": "Burkina Faso",
  "BGR": "Bulgaria",
  "BHR": "Bahrain",
  "BDI": "Burundi",
  "BEN": "Benin",
  "BRN": "Brunei Darussalam",
  "BOL": "Bolivia",
  "BRA": "Brazil",
  "BHS": "Bahamas",
  "BTN": "Bhutan",
  "BWA": "Botswana",
  "BLR": "Belarus",
  "BLZ": "Belize",
  "CAN": "Canada",
  "COD": "Democratic Republic of the Congo",
  "CAF": "Central African Republcoic",
  "COG": "Congo",
  "CHE": "Switzerland",
  "CIV": "Côte d'Ivoire",
  "CHL": "Chile",
  "CMR": "Cameroon",
  "CHN": "China",
  "COL": "Colombia",
  "CRI": "Costa Rica",
  "CUB": "Cuba",
  "CPV": "Cabo Verde",
  "CYP": "Cyprus",
  "CZE": "Czech Republic",
  "DEU": "Germany",
  "DJI": "Djibouti",
  "DNK": "Denmark",
  "DMA": "Dominica",
  "DOM": "Dominican Republic",
  "DZA": "Algeria",
  "EUR": "European Union",
  "ECU": "Ecuador",
  "EST": "Estonia",
  "ESH": "Sahrawi",
  "EGY": "Egypt",
  "ERI": "Eritrea",
  "ESP": "Spain",
  "ETH": "Ethiopia",
  "FIN": "Finland",
  "FJI": "Fiji",
  "FSM": "Micronesia",
  "FRA": "France",
  "GAB": "Gabon",
  "GBR": "United Kingdom",
  "GRD": "Grenada",
  "GEO": "Georgia",
  "GHA": "Ghana",
  "GMB": "Gambia",
  "GIN": "Guinea",
  "GNQ": "Equatorial Guinea",
  "GRC": "Greece",
  "GTM": "Guatemala",
  "GNB": "Guinea-Bissau",
  "GUY": "Guyana",
  "HND": "Honduras",
  "HRV": "Croatia",
  "HTI": "Haiti",
  "HUN": "Hungary",
  "IDN": "Indonesia",
  "IRL": "Ireland",
  "ISR": "Israel",
  "IND": "India",
  "IRQ": "Iraq",
  "IRN": "Iran",
  "ISL": "Iceland",
  "ITA": "Italy",
  "JAM": "Jamaica",
  "JOR": "Jordan",
  "JPN": "Japan",
  "KEN": "Kenya",
  "KGZ": "Kyrgyzstan",
  "KHM": "Cambodia",
  "KIR": "Kiribati",
  "COM": "Comoros",
  "KNA": "St. Kitts and Nevis",
  "PRK": "Democratic Pepole's Repulic of Korea",
  "KOR": "Republic of Korea",
  "KWT": "Kuwait",
  "KAZ": "Kazakhstan",
  "LAO": "Lao PDR",
  "LBN": "Lebanon",
  "LCA": "Saint Lucia",
  "LIE": "Liechtenstein",
  "LKA": "Sri Lanka",
  "LBR": "Liberia",
  "LSO": "Lesotho",
  "LTU": "Lithuania",
  "LUX": "Luxembourg",
  "LVA": "Latvia",
  "LBY": "Libya",
  "MAR": "Morocco",
  "MCO": "Monaco",
  "MDA": "Moldova",
  "MNE": "Montenegro",
  "MDG": "Madagascar",
  "MHL": "Marshall Islands",
  "MKD": "North Macedonia",
  "MLI": "Mali",
  "MMR": "Myanmar",
  "MNG": "Mongolia",
  "MRT": "Mauritania",
  "MLT": "Malta",
  "MUS": "Mauritius",
  "MDV": "Maldives",
  "MWI": "Malawi",
  "MEX": "Mexico",
  "MYS": "Malaysia",
  "MOZ": "Mozambique",
  "NAM": "Namibia",
  "NER": "Niger",
  "NGA": "Nigeria",
  "NIC": "Nicaragua",
  "NLD": "Netherlands",
  "NOR": "Norway",
  "NPL": "Nepal",
  "NRU": "Nauru",
  "NZL": "New Zealand",
  "OMN": "Oman",
  "PAN": "Panama",
  "PER": "Peru",
  "PNG": "Papua New Guinea",
  "PHL": "Philippines",
  "PAK": "Pakistan",
  "POL": "Poland",
  "PSE": "Palestine",
  "PRT": "Portugal",
  "PLW": "Palau",
  "PRY": "Paraguay",
  "QAT": "Qatar",
  "ROU": "Romania",
  "SRB": "Serbia",
  "RUS": "Russian Federation",
  "RWA": "Rwanda",
  "SAU": "Saudi Arabia",
  "SLB": "Solomon Islands",
  "SYC": "Seychelles",
  "SDN": "Sudan",
  "SWE": "Sweden",
  "SGP": "Singapore",
  "SVN": "Slovenia",
  "SVK": "Slovakia",
  "SLE": "Sierra Leone",
  "SMR": "San Marino",
  "SEN": "Senegal",
  "SOM": "Somalia",
  "SUR": "Suriname",
  "SSD": "South Sudan",
  "STP": "Sao Tome and Principe",
  "SLV": "El Salvador",
  "SYR": "Syrian Arab Republic",
  "SWZ": "Eswatini",
  "TCD": "Chad",
  "TGO": "Togo",
  "THA": "Thailand",
  "TJK": "Tajikistan",
  "TLS": "Timor-Leste",
  "TKM": "Turkmenistan",
  "TUN": "Tunisia",
  "TON": "Tonga",
  "TUR": "Turkey",
  "TTO": "Trinidad and Tobago",
  "TUV": "Tuvalu",
  "TZA": "Tanzania",
  "UKR": "Ukraine",
  "UGA": "Uganda",
  "USA": "United States",
  "URY": "Uruguay",
  "UZB": "Uzbekistan",
  "VAT": "Holy See",
  "VCT": "St. Vincent and the Grenadines",
  "VEN": "Venezuela",
  "VNM": "Vietnam",
  "VUT": "Vanuatu",
  "WSM": "Samoa",
  "YEM": "Yemen",
  "ZAF": "South Africa",
  "ZMB": "Zambia",
  "ZWE": "Zimbabwe",
};

final Map<String, String> AIPPM = {
  "AAP 00": "Arvind Kejriwal",
  "AAP 01": "Raghav Chaddha",
  "AAP 02": "Bhagwant Mann",
  "AAP 03": "Manish Sisodia",
  "ADS 00": "Anupriya Patel",
  "AIADMK 00": "EK Palaniswami",
  "AIMIM 00": "Asadudin Owaisi",
  "AITMC 00": "Mamata Banerjee",
  "AITMC 01": "Mahua Moitra",
  "AITMC 02": "Abhishek Banerjee",
  "BBSS 00": "Eknath Shinde",
  "BJD 00": "Naveen Patnaik",
  "BJP 00": "Narendra Modi",
  "BJP 01": "Amit Shah",
  "BJP 02": "Rajnath Singh",
  "BJP 03": "Nitin Gadkari",
  "BJP 04": "Nirmala Sitharaman",
  "BJP 05": "Dharmendra Pradhan",
  "BJP 06": "Jitendra Singh",
  "BJP 07": "Anurag Singh Thakur",
  "BJP 08": "Gajendra Singh Shekhawat",
  "BJP 09": "Aswini Vaishnav",
  "BJP 10": "Smriti Irani",
  "BJP 11": "Subramanaiam Jaishankar",
  "BJP 12": "Giriraj Singh",
  "BJP 13": "Hardeep Singh Puri",
  "BJP 14": "Jyotiraditya Scindia",
  "BJP 15": "Shivraj Singh Chouhan",
  "BJP 16": "Yogi Adityanath",
  "BJP 17": "Piyush Goyal",
  "BJP 18": "Kiren Rijiju",
  "BJP 19": "Narayan Rane",
  "BJP 20": "Parmod Sawant",
  "BJP 21": "Manohar Lal Khattar",
  "BJP 22": "Bhupendra Yadav",
  "BJP 23": "Bhupendra Patel",
  "BJP 24": "Devendra Fadnavis",
  "BJP 25": "Basavraj Bommai",
  "BJP 26": "Himanta Biswa Sharma",
  "BJP 27": "Pushkar Singh Dhami",
  "BJP 28": "Pema Khandu",
  "BJP 29": "JP Nadda",
  "BJP 30": "Sarbananda Sonowal",
  "BJP 31": "Meneka Gandhi",
  "BJP 32": "Ravishankar Prasad",
  "BJP 33": "Harshvardhan",
  "BJP 34": "Parvesh Verma",
  "BJP 35": "Meenakshi Lekhi",
  "BJP 36": "Mansukh Mandaviya",
  "BJP 37": "Manoj Tiwari",
  "BJP 38": "Narendra Singh Tomar",
  "BJP 39": "Som Parkash",
  "BRS 00": "K Chandrashekhar",
  "BSP 00": "Mayawati",
  "CPI 00": "D Raja",
  "CPI-M 00": "Seetaram Yechury",
  "CPI-M 01": "Pinarayi Vijayan",
  "DMK 00": "MK Stalin",
  "DMK 01": "TR Baalu",
  "INC 00": "Adhir Ranjan Choudhary",
  "INC 01": "Rahul Gandhi",
  "INC 02": "Sonia Gandhi",
  "INC 03": "Priyanka Gandhi",
  "INC 04": "Mallikarjuna Kharge",
  "INC 05": "Shashi Tharoor",
  "INC 06": "P. Chidambram",
  "INC 07": "Ashok Gehlot",
  "INC 08": "Bhupesh Baghel",
  "INC 09": "Kapil Sibbal",
  "INC 10": "Manmohan Singh",
  "INC 11": "Gaurav Gogoi",
  "INC 12": "Navjot Singh Sidhu",
  "INC 13": "Sachin Pilot",
  "INC 14": "Sukhwinder Singh Sukhu",
  "INC 15": "Randeep Surjewala",
  "INC 16": "K.C. Venugopal",
  "INC 17": "Bhupinder Singh Hooda",
  "INC 18": "Manish Tewari",
  "INC 19": "Prithvi Raj Chavan",
  "JDS 00": "HD Kumaraswamy",
  "JDU 00": "Nitish Kumar",
  "JMM 00": "Hemant Soren",
  "MNF 00": "Zoramthanga",
  "NC 00": "Omar Abdullah",
  "NC 01": "Farrukh Abdullah",
  "NCP 00": "Supriya Sule",
  "NCP 01": "Ajit Pawar",
  "NCP 02": "Sharad Pawar",
  "NDPP 00": "Neiphiu Rio",
  "NPP 00": "Conrad Sangma",
  "PDP 00": "Mehbooba Mufti",
  "RJD 00": "Lalu Prasad Yadav",
  "RJD 01": "Tejasvi Yadav",
  "RJD 02": "Tej Pratap Yadav",
  "SAD 00": "Sukhbir Singh Badal",
  "SKM 00": "Prem Singh Tamang",
  "SP 00": "Akhilesh Yadav",
  "SS 00": "Uddhav Thackarey",
  "SS 01": "Sanjay Raut",
  "YSRCP 00": "YS Jagan Mohan Reddy",
};

// TODO: Others Flags
// TODO: Strech Paty Icons

final Map<String, String> DELEGATES = {...COUNTRIES, ...AIPPM};

const Map<String, List<String>> COMMITTEES = {
  "UNSC": [
    "BEL",
    "CHN",
    "DEU",
    "DOM",
    "EST",
    "FRA",
    "GBR",
    "IDN",
    "NER",
    "RUS",
    "TUN",
    "USA",
    "VCT",
    "VNM",
    "ZAF",
  ],
  "ECOSOC": [
    "AGO",
    "ARM",
    "AUS",
    "BEN",
    "BGD",
    "BLR",
    "BRA",
    "BWA",
    "CAN",
    "CHE",
    "CHN",
    "COG",
    "COL",
    "DEU",
    "ECU",
    "EGY",
    "ESP",
    "ETH",
    "FIN",
    "FRA",
    "GAB",
    "GHA",
    "IND",
    "IRL",
    "IRN",
    "JAM",
    "JPN",
    "KEN",
    "KOR",
    "LUX",
    "LVA",
    "MAR",
    "MEX",
    "MLI",
    "MLT",
    "MNE",
    "MWI",
    "NIC",
    "NLD",
    "NOR",
    "PAK",
    "PAN",
    "PHL",
    "PRY",
    "RUS",
    "SAU",
    "SDN",
    "SLV",
    "TGO",
    "THA",
    "TKM",
    "UKR",
    "URY",
    "USA"
  ],
  "WHO": [
    "ARE",
    "ARG",
    "AUS",
    "AUT",
    "BFA",
    "BGD",
    "BWA",
    "CHL",
    "CHN",
    "COL",
    "DEU",
    "DJI",
    "FIN",
    "GAB",
    "GBR",
    "GHA",
    "GNB",
    "GRD",
    "GUY",
    "IDN",
    "IND",
    "ISR",
    "KEN",
    "KOR",
    "MDG",
    "OMN",
    "ROU",
    "RUS",
    "SDN",
    "SGP",
    "TJK",
    "TON",
    "TUN",
    "USA"
  ],
  "UNHCR": [
    "AFG",
    "AGO",
    "ALB",
    "ARE",
    "ARG",
    "ARM",
    "AUS",
    "AUT",
    "AZE",
    "BDI",
    "BEL",
    "BEN",
    "BFA",
    "BGD",
    "BGR",
    "BHS",
    "BIH",
    "BLR",
    "BLZ",
    "BOL",
    "BRA",
    "BWA",
    "CAF",
    "CAN",
    "CHE",
    "CHL",
    "CHN",
    "CIV",
    "CMR",
    "COD",
    "COG",
    "COL",
    "COM",
    "CRI",
    "CUB",
    "CYP",
    "CZE",
    "DEU",
    "DJI",
    "DNK",
    "DOM",
    "DZA",
    "ECU",
    "EGY",
    "ESP",
    "EST",
    "ETH",
    "FIN",
    "FJI",
    "FRA",
    "GAB",
    "GBR",
    "GEO",
    "GHA",
    "GIN",
    "GMB",
    "GNB",
    "GNQ",
    "GRC",
    "GTM",
    "GUY",
    "VAT",
    "HND",
    "HRV",
    "HTI",
    "HUN",
    "IDN",
    "IND",
    "IRL",
    "IRN",
    "IRQ",
    "ISL",
    "ISR",
    "ITA",
    "JOR",
    "JPN",
    "KAZ",
    "KEN",
    "KGZ",
    "KNA",
    "KOR",
    "KWT",
    "LAO",
    "LBN",
    "LBR",
    "LBY",
    "LKA",
    "LSO",
    "LTU",
    "LUX",
    "LVA",
    "MAR",
    "MCO",
    "MDA",
    "MDG",
    "MEX",
    "MKD",
    "MLI",
    "MLT",
    "MMR",
    "MNE",
    "MOZ",
    "MRT",
    "MUS",
    "MWI",
    "MYS",
    "NAM",
    "NER",
    "NGA",
    "NIC",
    "NLD",
    "NOR",
    "NPL",
    "NZL",
    "PAK",
    "PAN",
    "PER",
    "PHL",
    "POL",
    "PRT",
    "PRY",
    "QAT",
    "ROU",
    "RUS",
    "RWA",
    "SAU",
    "SDN",
    "SEN",
    "SGP",
    "SLB",
    "SLE",
    "SLV",
    "SOM",
    "SRB",
    "SSD",
    "SVK",
    "SVN",
    "SWE",
    "SWZ",
    "SYC",
    "SYR",
    "TCD",
    "TGO",
    "THA",
    "TJK",
    "TKM",
    "TTO",
    "TUN",
    "TUR",
    "TZA",
    "UGA",
    "UKR",
    "URY",
    "USA",
    "VEN",
    "VNM",
    "YEM",
    "ZAF",
    "ZMB",
    "ZWE"
  ],
  "UNHRC": [
    "AFG",
    "AGO",
    "ARE",
    "ARG",
    "AUS",
    "AUT",
    "BFA",
    "BGD",
    "BGR",
    "BHR",
    "BHS",
    "BRA",
    "CHL",
    "CHN",
    "CMR",
    "COD",
    "CUB",
    "CZE",
    "DNK",
    "EGY",
    "ERI",
    "ESP",
    "FJI",
    "GBR",
    "HRV",
    "HUN",
    "IRQ",
    "ISL",
    "ITA",
    "JPN",
    "MEX",
    "NGA",
    "NPL",
    "PAK",
    "PER",
    "PHL",
    "QAT",
    "RWA",
    "SAU",
    "SEN",
    "SOM",
    "SVK",
    "TGO",
    "TUN",
    "UKR",
    "URY",
    "ZAF"
  ],
  "UNICEF": [
    "BDI",
    "BEN",
    "BGD",
    "BRA",
    "CAN",
    "CHE",
    "CHN",
    "CMR",
    "COL",
    "CUB",
    "DEU",
    "DJI",
    "DNK",
    "ESP",
    "EST",
    "GBR",
    "GHA",
    "IRL",
    "JPN",
    "KOR",
    "LTU",
    "MAR",
    "MDA",
    "MEX",
    "MNG",
    "NOR",
    "NZL",
    "PAK",
    "PRY",
    "RUS",
    "SDN",
    "SWE",
    "TKM",
    "USA",
    "YEM",
    "ZWE"
  ],
  "UNGA": [
    "AFG",
    "AGO",
    "ALB",
    "AND",
    "ARE",
    "ARG",
    "ARM",
    "ATG",
    "AUS",
    "AUT",
    "AZE",
    "BDI",
    "BEL",
    "BEN",
    "BFA",
    "BGD",
    "BGR",
    "BHR",
    "BHS",
    "BIH",
    "BLR",
    "BLZ",
    "BOL",
    "BRA",
    "BRB",
    "BRN",
    "BTN",
    "BWA",
    "CAF",
    "CAN",
    "CHE",
    "CHL",
    "CHN",
    "CIV",
    "CMR",
    "COD",
    "COG",
    "COL",
    "COM",
    "CPV",
    "CRI",
    "CUB",
    "CYP",
    "CZE",
    "DEU",
    "DJI",
    "DMA",
    "DNK",
    "DOM",
    "DZA",
    "ECU",
    "EGY",
    "ERI",
    "ESP",
    "EST",
    "ETH",
    "FIN",
    "FJI",
    "FRA",
    "FSM",
    "GAB",
    "GBR",
    "GEO",
    "GHA",
    "GIN",
    "GMB",
    "GNB",
    "GNQ",
    "GRC",
    "GRD",
    "GTM",
    "GUY",
    "VAT",
    "HND",
    "HRV",
    "HTI",
    "HUN",
    "IDN",
    "IND",
    "IRL",
    "IRN",
    "IRQ",
    "ISL",
    "ISR",
    "ITA",
    "JAM",
    "JOR",
    "JPN",
    "KAZ",
    "KEN",
    "KGZ",
    "KHM",
    "KIR",
    "KNA",
    "KOR",
    "KWT",
    "LAO",
    "LBN",
    "LBR",
    "LBY",
    "LCA",
    "LIE",
    "LKA",
    "LSO",
    "LTU",
    "LUX",
    "LVA",
    "MAR",
    "MCO",
    "MDA",
    "MDG",
    "MDV",
    "MEX",
    "MHL",
    "MKD",
    "MLI",
    "MLT",
    "MMR",
    "MNE",
    "MNG",
    "MOZ",
    "MRT",
    "MUS",
    "MWI",
    "MYS",
    "NAM",
    "NER",
    "NGA",
    "NIC",
    "NLD",
    "NOR",
    "NPL",
    "NRU",
    "NZL",
    "OMN",
    "PAK",
    "PAN",
    "PER",
    "PHL",
    "PLW",
    "PNG",
    "POL",
    "PRK",
    "PRT",
    "PRY",
    "PSE",
    "QAT",
    "ROU",
    "RUS",
    "RWA",
    "SAU",
    "SDN",
    "SEN",
    "SGP",
    "SLB",
    "SLE",
    "SLV",
    "SMR",
    "SOM",
    "SRB",
    "SSD",
    "STP",
    "SUR",
    "SVK",
    "SVN",
    "SWE",
    "SWZ",
    "SYC",
    "SYR",
    "TCD",
    "TGO",
    "THA",
    "TJK",
    "TKM",
    "TLS",
    "TON",
    "TTO",
    "TUN",
    "TUR",
    "TUV",
    "TZA",
    "UGA",
    "UKR",
    "URY",
    "USA",
    "UZB",
    "VCT",
    "VEN",
    "VNM",
    "VUT",
    "WSM",
    "YEM",
    "ZAF",
    "ZMB",
    "ZWE"
  ],
  "ASEAN": [
    "BRN",
    "IDN",
    "KHM",
    "LAO",
    "MMR",
    "MYS",
    "PHL",
    "PNG",
    "SGP",
    "THA",
    "VNM"
  ],
  "NATO": [
    "ALB",
    "BEL",
    "BGR",
    "CAN",
    "CZE",
    "DEU",
    "DNK",
    "ESP",
    "EST",
    "FRA",
    "GBR",
    "GRC",
    "HRV",
    "HUN",
    "ISL",
    "ITA",
    "LTU",
    "LUX",
    "LVA",
    "MKD",
    "MNE",
    "NLD",
    "NOR",
    "POL",
    "PRT",
    "ROU",
    "SVK",
    "SVN",
    "TUR",
    "USA"
  ],
  "EU": [
    "AUT",
    "BEL",
    "BGR",
    "CYP",
    "CZE",
    "DEU",
    "DNK",
    "ESP",
    "EST",
    "FIN",
    "FRA",
    "GRC",
    "HRV",
    "HUN",
    "IRL",
    "ITA",
    "LTU",
    "LUX",
    "LVA",
    "MLT",
    "NLD",
    "POL",
    "PRT",
    "ROU",
    "SVK",
    "SVN",
    "SWE"
  ],
  "G20": [
    "ARG",
    "AUS",
    "BRA",
    "CAN",
    "CHN",
    "EUR",
    "DEU",
    "FRA",
    "GBR",
    "IDN",
    "IND",
    "ITA",
    "JPN",
    "KOR",
    "MEX",
    "RUS",
    "SAU",
    "TUR",
    "USA",
    "ZAF"
  ],
  "AU": [
    "AGO",
    "BDI",
    "BEN",
    "BFA",
    "BWA",
    "CAF",
    "CIV",
    "CMR",
    "COD",
    "COG",
    "COM",
    "CPV",
    "DJI",
    "DZA",
    "EGY",
    "ERI",
    "ETH",
    "GAB",
    "GHA",
    "GIN",
    "GMB",
    "GNB",
    "GNQ",
    "KEN",
    "LBR",
    "LBY",
    "LSO",
    "MAR",
    "MDG",
    "MLI",
    "MOZ",
    "MRT",
    "MUS",
    "MWI",
    "NAM",
    "NER",
    "NGA",
    "RWA",
    "ESH",
    "SDN",
    "SEN",
    "SLE",
    "SOM",
    "SSD",
    "STP",
    "SWZ",
    "SYC",
    "TCD",
    "TGO",
    "TUN",
    "TZA",
    "UGA",
    "ZAF",
    "ZMB",
    "ZWE"
  ],
  "AIPPM 1": [
    "AAP 00",
    "AAP 01",
    "ADS 00",
    "AIADMK 00",
    "AIMIM 00",
    "AITMC 00",
    "AITMC 01",
    "BBSS 00",
    "BJD 00",
    "BJP 00",
    "BJP 01",
    "BJP 02",
    "BJP 03",
    "BJP 04",
    "BJP 05",
    "BJP 06",
    "BJP 07",
    "BJP 08",
    "BJP 09",
    "BJP 10",
    "BJP 11",
    "BJP 12",
    "BJP 13",
    "BJP 14",
    "BJP 15",
    "BJP 16",
    "BJP 17",
    "BJP 18",
    "BRS 00",
    "BSP 00",
    "CPI-M 00",
    "DMK 00",
    "INC 00",
    "INC 01",
    "INC 02",
    "INC 03",
    "INC 04",
    "INC 05",
    "INC 07",
    "INC 08",
    "INC 09",
    "JDU 00",
    "NCP 02",
    "NPP 00",
    "SAD 00",
    "SP 00",
    "YSRCP 00",
  ],
  "AIPPM 2": [
    "AAP 00",
    "AAP 01",
    "AAP 02",
    "AAP 03",
    "ADS 00",
    "AIADMK 00",
    "AIMIM 00",
    "AITMC 00",
    "AITMC 01",
    "AITMC 02",
    "BBSS 00",
    "BJD 00",
    "BJP 00",
    "BJP 01",
    "BJP 02",
    "BJP 03",
    "BJP 04",
    "BJP 05",
    "BJP 06",
    "BJP 07",
    "BJP 08",
    "BJP 09",
    "BJP 10",
    "BJP 12",
    "BJP 13",
    "BJP 14",
    "BJP 15",
    "BJP 16",
    "BJP 17",
    "BJP 18",
    "BJP 19",
    "BJP 20",
    "BJP 21",
    "BJP 22",
    "BJP 23",
    "BJP 24",
    "BJP 25",
    "BJP 26",
    "BJP 27",
    "BJP 28",
    "BJP 29",
    "BJP 30",
    "BJP 31",
    "BJP 32",
    "BJP 33",
    "BJP 34",
    "BJP 35",
    "BJP 36",
    "BJP 37",
    "BJP 38",
    "BJP 39",
    "BRS 00",
    "BSP 00",
    "CPI 00",
    "CPI-M 00",
    "CPI-M 01",
    "DMK 00",
    "DMK 01",
    "INC 00",
    "INC 01",
    "INC 02",
    "INC 03",
    "INC 04",
    "INC 05",
    "INC 06",
    "INC 07",
    "INC 08",
    "INC 09",
    "INC 10",
    "INC 11",
    "INC 12",
    "INC 13",
    "INC 14",
    "INC 15",
    "INC 16",
    "INC 17",
    "INC 18",
    "INC 19",
    "JDS 00",
    "JDU 00",
    "JMM 00",
    "MNF 00",
    "NC 00",
    "NC 01",
    "NCP 00",
    "NCP 01",
    "NCP 02",
    "NDPP 00",
    "NPP 00",
    "PDP 00",
    "RJD 00",
    "RJD 01",
    "RJD 02",
    "SAD 00",
    "SKM 00",
    "SP 00",
    "SS 00",
    "SS 01",
    "YSRCP 00",
  ],
};
