// ignore_for_file: non_constant_identifier_names
// TODO: Drag & Drop

final Map<String, String> COUNTRIES = {
  "AND": "Andorra",
  "ARE": "United Arab Emirates",
  "AFG": "Afghanistan",
  "ATG": "Antigua and Barbuda",
  "ALB": "Albania",
  "ARM": "Armenia",
  "AGO": "Angola",
  "ARG": "Argentina",
  "AUT": "Austria",
  "AUS": "Australia",
  "AZE": "Azerbaijan",
  "BIH": "Bosnia and Herzegovina",
  "BRB": "Barbados",
  "BGD": "Bangladesh",
  "BEL": "Belgium",
  "BFA": "Burkina Faso",
  "BGR": "Bulgaria",
  "BHR": "Bahrain",
  "BDI": "Burundi",
  "BEN": "Benin",
  "BRN": "Brunei Darussalam",
  "BOL": "Bolivia",
  "BRA": "Brazil",
  "BHS": "Bahamas",
  "BTN": "Bhutan",
  "BWA": "Botswana",
  "BLR": "Belarus",
  "BLZ": "Belize",
  "CAN": "Canada",
  "COD": "Democratic Republic of the Congo",
  "CAF": "Central African Republcoic",
  "COG": "Congo",
  "CHE": "Switzerland",
  "CIV": "Côte d'Ivoire",
  "CHL": "Chile",
  "CMR": "Cameroon",
  "CHN": "China",
  "COL": "Colombia",
  "CRI": "Costa Rica",
  "CUB": "Cuba",
  "CPV": "Cabo Verde",
  "CYP": "Cyprus",
  "CZE": "Czech Republic",
  "DEU": "Germany",
  "DJI": "Djibouti",
  "DNK": "Denmark",
  "DMA": "Dominica",
  "DOM": "Dominican Republic",
  "DZA": "Algeria",
  "EUR": "European Union",
  "ECU": "Ecuador",
  "EST": "Estonia",
  "ESH": "Sahrawi",
  "EGY": "Egypt",
  "ERI": "Eritrea",
  "ESP": "Spain",
  "ETH": "Ethiopia",
  "FIN": "Finland",
  "FJI": "Fiji",
  "FSM": "Micronesia",
  "FRA": "France",
  "GAB": "Gabon",
  "GBR": "United Kingdom",
  "GRD": "Grenada",
  "GEO": "Georgia",
  "GHA": "Ghana",
  "GMB": "Gambia",
  "GIN": "Guinea",
  "GNQ": "Equatorial Guinea",
  "GRC": "Greece",
  "GTM": "Guatemala",
  "GNB": "Guinea-Bissau",
  "GUY": "Guyana",
  "HND": "Honduras",
  "HRV": "Croatia",
  "HTI": "Haiti",
  "HUN": "Hungary",
  "IDN": "Indonesia",
  "IRL": "Ireland",
  "ISR": "Israel",
  "IND": "India",
  "IRQ": "Iraq",
  "IRN": "Iran",
  "ISL": "Iceland",
  "ITA": "Italy",
  "JAM": "Jamaica",
  "JOR": "Jordan",
  "JPN": "Japan",
  "KEN": "Kenya",
  "KGZ": "Kyrgyzstan",
  "KHM": "Cambodia",
  "KIR": "Kiribati",
  "COM": "Comoros",
  "KNA": "St. Kitts and Nevis",
  "PRK": "Democratic Pepole's Repulic of Korea",
  "KOR": "Republic of Korea",
  "KWT": "Kuwait",
  "KAZ": "Kazakhstan",
  "LAO": "Lao PDR",
  "LBN": "Lebanon",
  "LCA": "Saint Lucia",
  "LIE": "Liechtenstein",
  "LKA": "Sri Lanka",
  "LBR": "Liberia",
  "LSO": "Lesotho",
  "LTU": "Lithuania",
  "LUX": "Luxembourg",
  "LVA": "Latvia",
  "LBY": "Libya",
  "MAR": "Morocco",
  "MCO": "Monaco",
  "MDA": "Moldova",
  "MNE": "Montenegro",
  "MDG": "Madagascar",
  "MHL": "Marshall Islands",
  "MKD": "North Macedonia",
  "MLI": "Mali",
  "MMR": "Myanmar",
  "MNG": "Mongolia",
  "MRT": "Mauritania",
  "MLT": "Malta",
  "MUS": "Mauritius",
  "MDV": "Maldives",
  "MWI": "Malawi",
  "MEX": "Mexico",
  "MYS": "Malaysia",
  "MOZ": "Mozambique",
  "NAM": "Namibia",
  "NER": "Niger",
  "NGA": "Nigeria",
  "NIC": "Nicaragua",
  "NLD": "Netherlands",
  "NOR": "Norway",
  "NPL": "Nepal",
  "NRU": "Nauru",
  "NZL": "New Zealand",
  "OMN": "Oman",
  "PAN": "Panama",
  "PER": "Peru",
  "PNG": "Papua New Guinea",
  "PHL": "Philippines",
  "PAK": "Pakistan",
  "POL": "Poland",
  "PSE": "Palestine",
  "PRT": "Portugal",
  "PLW": "Palau",
  "PRY": "Paraguay",
  "QAT": "Qatar",
  "ROU": "Romania",
  "SRB": "Serbia",
  "RUS": "Russian Federation",
  "RWA": "Rwanda",
  "SAU": "Saudi Arabia",
  "SLB": "Solomon Islands",
  "SYC": "Seychelles",
  "SDN": "Sudan",
  "SWE": "Sweden",
  "SGP": "Singapore",
  "SVN": "Slovenia",
  "SVK": "Slovakia",
  "SLE": "Sierra Leone",
  "SMR": "San Marino",
  "SEN": "Senegal",
  "SOM": "Somalia",
  "SUR": "Suriname",
  "SSD": "South Sudan",
  "STP": "Sao Tome and Principe",
  "SLV": "El Salvador",
  "SYR": "Syrian Arab Republic",
  "SWZ": "Eswatini",
  "TCD": "Chad",
  "TGO": "Togo",
  "THA": "Thailand",
  "TJK": "Tajikistan",
  "TLS": "Timor-Leste",
  "TKM": "Turkmenistan",
  "TUN": "Tunisia",
  "TON": "Tonga",
  "TUR": "Turkey",
  "TTO": "Trinidad and Tobago",
  "TUV": "Tuvalu",
  "TZA": "Tanzania",
  "UKR": "Ukraine",
  "UGA": "Uganda",
  "USA": "United States",
  "URY": "Uruguay",
  "UZB": "Uzbekistan",
  "VAT": "Holy See",
  "VCT": "St. Vincent and the Grenadines",
  "VEN": "Venezuela",
  "VNM": "Vietnam",
  "VUT": "Vanuatu",
  "WSM": "Samoa",
  "YEM": "Yemen",
  "ZAF": "South Africa",
  "ZMB": "Zambia",
  "ZWE": "Zimbabwe",
};

final Map<String, String> AIPPM = {
  "AAP 0": "Arvind Kejriwal",
  "AAP 1": "Raghav Chaddha",
  "AAP 2": "Bhagwant Mann",
  "AAP 3": "Manish Sisodia",
  "ADS 0": "Anupriya Patel",
  "AIADMK 0": "EK Palaniswami",
  "AIMIM 0": "Asadudin Owaisi",
  "AITNC 0": "Mamata Banerjee",
  "AITNC 1": "Mahua Moitra",
  "AITNC 2": "Abhishek Banerjee",
  "BBSS 0": "Eknath Shinde",
  "BJD 0": "Naveen Patnaik",
  "BJP 0": "Narendra Modi",
  "BJP 1": "Amit Shah",
  "BJP 10": "Smriti Irani",
  "BJP 11": "Subramanaiam Jaishankar",
  "BJP 12": "Giriraj Singh",
  "BJP 13": "Hardeep Singh Puri",
  "BJP 14": "Jyotiraditya Scindia",
  "BJP 15": "Shivraj Singh Chouhan",
  "BJP 16": "Yogi Adityanath",
  "BJP 17": "Piyush Goyal",
  "BJP 18": "Kiren Rijiju",
  "BJP 19": "Narayan Rane",
  "BJP 2": "Rajnath Singh",
  "BJP 20": "Parmod Sawant",
  "BJP 21": "Manohar Lal Khattar",
  "BJP 22": "Bhupendra Yadav",
  "BJP 23": "Bhupendra Patel",
  "BJP 24": "Devendra Fadnavis",
  "BJP 25": "Basavraj Bommai",
  "BJP 26": "Himanta Biswa Sharma",
  "BJP 27": "Pushkar Singh Dhami",
  "BJP 28": "Pema Khandu",
  "BJP 29": "JP Nadda",
  "BJP 3": "Nitin Gadkari",
  "BJP 30": "Sarbananda Sonowal",
  "BJP 31": "Meneka Gandhi",
  "BJP 32": "Ravishankar Prasad",
  "BJP 33": "Harshvardhan",
  "BJP 34": "Parvesh Verma",
  "BJP 35": "Meenakshi Lekhi",
  "BJP 36": "Mansukh Mandaviya",
  "BJP 37": "Manoj Tiwari",
  "BJP 38": "Narendra Singh Tomar",
  "BJP 39": "Som Parkash",
  "BJP 4": "Nirmala Sitharaman",
  "BJP 5": "Dharmendra Pradhan",
  "BJP 6": "Jitendra Singh",
  "BJP 7": "Anurag Singh Thakur",
  "BJP 8": "Gajendra Singh Shekhawat",
  "BJP 9": "Aswini Vaishnav",
  "BRS 0": "K Chandrashekhar",
  "BSP 0": "Mayawati",
  "CPI 0": "D Raja",
  "CPI-M 0": "Seetaram Yechury",
  "CPI-M 1": "Pinarayi Vijayan",
  "DMK 0": "MK Stalin",
  "DMK 1": "TR Baalu",
  "INC 0": "Adhir Ranjan Choudhary",
  "INC 1": "Rahul Gandhi",
  "INC 10": "Manmohan Singh",
  "INC 11": "Gaurav Gogoi",
  "INC 12": "Navjot Singh Sidhu",
  "INC 13": "Sachin Pilot",
  "INC 14": "Sukhwinder Singh Sukhu",
  "INC 15": "Randeep Surjewala",
  "INC 16": "K.C. Venugopal",
  "INC 17": "Bhupinder Singh Hooda",
  "INC 18": "Manish Tewari",
  "INC 19": "Prithvi Raj Chavan",
  "INC 2": "Sonia Gandhi",
  "INC 3": "Priyanka Gandhi",
  "INC 4": "Mallikarjuna Kharge",
  "INC 5": "Shashi Tharoor",
  "INC 6": "P. Chidambram",
  "INC 7": "Ashok Gehlot",
  "INC 8": "Bhupesh Baghel",
  "INC 9": "Kapil Sibbal",
  "JDS 0": "HD Kumaraswamy",
  "JDU 0": "Nitish Kumar",
  "JMM 0": "Hemant Soren",
  "MNF 0": "Zoramthanga",
  "NCP 0": "Omar Abdullah",
  "NCP 1": "Supriya Sule",
  "NCP 2": "Ajit Pawar",
  "NCP 3": "Sharad Pawar",
  "NCP 4": "Farrukh Abdullah",
  "NDPP 0": "Neiphiu Rio",
  "NPP 0": "Conrad Sangma",
  "PDP 0": "Mehbooba Mufti",
  "RJD 0": "Lalu Prasad Yadav",
  "RJD 1": "Tejasvi Yadav",
  "RJD 2": "Tej Pratap Yadav",
  "SAD 0": "Sukhbir Singh Badal",
  "SKM 0": "Prem Singh Tamang",
  "SP 0": "Akhilesh Yadav",
  "SS 0": "Uddhav Thackarey",
  "SS 1": "Sanjay Raut",
  "YSRCP 0": "YS Jagan Mohan Reddy",
};

// TODO: AIMIM, RJD, PDP, SP, ADS & Others Flags
// TODO: Strech Paty Icons
// TODO: Check These: @Lovish

final Map<String, String> DELEGATES = {...COUNTRIES, ...AIPPM};

const Map<String, List<String>> COMMITTEES = {
  "UNSC": [
    "BEL",
    "CHN",
    "DEU",
    "DOM",
    "EST",
    "FRA",
    "GBR",
    "IDN",
    "NER",
    "RUS",
    "TUN",
    "USA",
    "VCT",
    "VNM",
    "ZAF",
  ],
  "ECOSOC": [
    "AGO",
    "ARM",
    "AUS",
    "BEN",
    "BGD",
    "BLR",
    "BRA",
    "BWA",
    "CAN",
    "CHE",
    "CHN",
    "COG",
    "COL",
    "DEU",
    "ECU",
    "EGY",
    "ESP",
    "ETH",
    "FIN",
    "FRA",
    "GAB",
    "GHA",
    "IND",
    "IRL",
    "IRN",
    "JAM",
    "JPN",
    "KEN",
    "KOR",
    "LUX",
    "LVA",
    "MAR",
    "MEX",
    "MLI",
    "MLT",
    "MNE",
    "MWI",
    "NIC",
    "NLD",
    "NOR",
    "PAK",
    "PAN",
    "PHL",
    "PRY",
    "RUS",
    "SAU",
    "SDN",
    "SLV",
    "TGO",
    "THA",
    "TKM",
    "UKR",
    "URY",
    "USA"
  ],
  "WHO": [
    "ARE",
    "ARG",
    "AUS",
    "AUT",
    "BFA",
    "BGD",
    "BWA",
    "CHL",
    "CHN",
    "COL",
    "DEU",
    "DJI",
    "FIN",
    "GAB",
    "GBR",
    "GHA",
    "GNB",
    "GRD",
    "GUY",
    "IDN",
    "IND",
    "ISR",
    "KEN",
    "KOR",
    "MDG",
    "OMN",
    "ROU",
    "RUS",
    "SDN",
    "SGP",
    "TJK",
    "TON",
    "TUN",
    "USA"
  ],
  "UNHCR": [
    "AFG",
    "AGO",
    "ALB",
    "ARE",
    "ARG",
    "ARM",
    "AUS",
    "AUT",
    "AZE",
    "BDI",
    "BEL",
    "BEN",
    "BFA",
    "BGD",
    "BGR",
    "BHS",
    "BIH",
    "BLR",
    "BLZ",
    "BOL",
    "BRA",
    "BWA",
    "CAF",
    "CAN",
    "CHE",
    "CHL",
    "CHN",
    "CIV",
    "CMR",
    "COD",
    "COG",
    "COL",
    "COM",
    "CRI",
    "CUB",
    "CYP",
    "CZE",
    "DEU",
    "DJI",
    "DNK",
    "DOM",
    "DZA",
    "ECU",
    "EGY",
    "ESP",
    "EST",
    "ETH",
    "FIN",
    "FJI",
    "FRA",
    "GAB",
    "GBR",
    "GEO",
    "GHA",
    "GIN",
    "GMB",
    "GNB",
    "GNQ",
    "GRC",
    "GTM",
    "GUY",
    "VAT",
    "HND",
    "HRV",
    "HTI",
    "HUN",
    "IDN",
    "IND",
    "IRL",
    "IRN",
    "IRQ",
    "ISL",
    "ISR",
    "ITA",
    "JOR",
    "JPN",
    "KAZ",
    "KEN",
    "KGZ",
    "KNA",
    "KOR",
    "KWT",
    "LAO",
    "LBN",
    "LBR",
    "LBY",
    "LKA",
    "LSO",
    "LTU",
    "LUX",
    "LVA",
    "MAR",
    "MCO",
    "MDA",
    "MDG",
    "MEX",
    "MKD",
    "MLI",
    "MLT",
    "MMR",
    "MNE",
    "MOZ",
    "MRT",
    "MUS",
    "MWI",
    "MYS",
    "NAM",
    "NER",
    "NGA",
    "NIC",
    "NLD",
    "NOR",
    "NPL",
    "NZL",
    "PAK",
    "PAN",
    "PER",
    "PHL",
    "POL",
    "PRT",
    "PRY",
    "QAT",
    "ROU",
    "RUS",
    "RWA",
    "SAU",
    "SDN",
    "SEN",
    "SGP",
    "SLB",
    "SLE",
    "SLV",
    "SOM",
    "SRB",
    "SSD",
    "SVK",
    "SVN",
    "SWE",
    "SWZ",
    "SYC",
    "SYR",
    "TCD",
    "TGO",
    "THA",
    "TJK",
    "TKM",
    "TTO",
    "TUN",
    "TUR",
    "TZA",
    "UGA",
    "UKR",
    "URY",
    "USA",
    "VEN",
    "VNM",
    "YEM",
    "ZAF",
    "ZMB",
    "ZWE"
  ],
  "UNHRC": [
    "AFG",
    "AGO",
    "ARE",
    "ARG",
    "AUS",
    "AUT",
    "BFA",
    "BGD",
    "BGR",
    "BHR",
    "BHS",
    "BRA",
    "CHL",
    "CHN",
    "CMR",
    "COD",
    "CUB",
    "CZE",
    "DNK",
    "EGY",
    "ERI",
    "ESP",
    "FJI",
    "GBR",
    "HRV",
    "HUN",
    "IRQ",
    "ISL",
    "ITA",
    "JPN",
    "MEX",
    "NGA",
    "NPL",
    "PAK",
    "PER",
    "PHL",
    "QAT",
    "RWA",
    "SAU",
    "SEN",
    "SOM",
    "SVK",
    "TGO",
    "TUN",
    "UKR",
    "URY",
    "ZAF"
  ],
  "UNICEF": [
    "BDI",
    "BEN",
    "BGD",
    "BRA",
    "CAN",
    "CHE",
    "CHN",
    "CMR",
    "COL",
    "CUB",
    "DEU",
    "DJI",
    "DNK",
    "ESP",
    "EST",
    "GBR",
    "GHA",
    "IRL",
    "JPN",
    "KOR",
    "LTU",
    "MAR",
    "MDA",
    "MEX",
    "MNG",
    "NOR",
    "NZL",
    "PAK",
    "PRY",
    "RUS",
    "SDN",
    "SWE",
    "TKM",
    "USA",
    "YEM",
    "ZWE"
  ],
  "UNGA": [
    "AFG",
    "AGO",
    "ALB",
    "AND",
    "ARE",
    "ARG",
    "ARM",
    "ATG",
    "AUS",
    "AUT",
    "AZE",
    "BDI",
    "BEL",
    "BEN",
    "BFA",
    "BGD",
    "BGR",
    "BHR",
    "BHS",
    "BIH",
    "BLR",
    "BLZ",
    "BOL",
    "BRA",
    "BRB",
    "BRN",
    "BTN",
    "BWA",
    "CAF",
    "CAN",
    "CHE",
    "CHL",
    "CHN",
    "CIV",
    "CMR",
    "COD",
    "COG",
    "COL",
    "COM",
    "CPV",
    "CRI",
    "CUB",
    "CYP",
    "CZE",
    "DEU",
    "DJI",
    "DMA",
    "DNK",
    "DOM",
    "DZA",
    "ECU",
    "EGY",
    "ERI",
    "ESP",
    "EST",
    "ETH",
    "FIN",
    "FJI",
    "FRA",
    "FSM",
    "GAB",
    "GBR",
    "GEO",
    "GHA",
    "GIN",
    "GMB",
    "GNB",
    "GNQ",
    "GRC",
    "GRD",
    "GTM",
    "GUY",
    "VAT",
    "HND",
    "HRV",
    "HTI",
    "HUN",
    "IDN",
    "IND",
    "IRL",
    "IRN",
    "IRQ",
    "ISL",
    "ISR",
    "ITA",
    "JAM",
    "JOR",
    "JPN",
    "KAZ",
    "KEN",
    "KGZ",
    "KHM",
    "KIR",
    "KNA",
    "KOR",
    "KWT",
    "LAO",
    "LBN",
    "LBR",
    "LBY",
    "LCA",
    "LIE",
    "LKA",
    "LSO",
    "LTU",
    "LUX",
    "LVA",
    "MAR",
    "MCO",
    "MDA",
    "MDG",
    "MDV",
    "MEX",
    "MHL",
    "MKD",
    "MLI",
    "MLT",
    "MMR",
    "MNE",
    "MNG",
    "MOZ",
    "MRT",
    "MUS",
    "MWI",
    "MYS",
    "NAM",
    "NER",
    "NGA",
    "NIC",
    "NLD",
    "NOR",
    "NPL",
    "NRU",
    "NZL",
    "OMN",
    "PAK",
    "PAN",
    "PER",
    "PHL",
    "PLW",
    "PNG",
    "POL",
    "PRK",
    "PRT",
    "PRY",
    "PSE",
    "QAT",
    "ROU",
    "RUS",
    "RWA",
    "SAU",
    "SDN",
    "SEN",
    "SGP",
    "SLB",
    "SLE",
    "SLV",
    "SMR",
    "SOM",
    "SRB",
    "SSD",
    "STP",
    "SUR",
    "SVK",
    "SVN",
    "SWE",
    "SWZ",
    "SYC",
    "SYR",
    "TCD",
    "TGO",
    "THA",
    "TJK",
    "TKM",
    "TLS",
    "TON",
    "TTO",
    "TUN",
    "TUR",
    "TUV",
    "TZA",
    "UGA",
    "UKR",
    "URY",
    "USA",
    "UZB",
    "VCT",
    "VEN",
    "VNM",
    "VUT",
    "WSM",
    "YEM",
    "ZAF",
    "ZMB",
    "ZWE"
  ],
  "ASEAN": [
    "BRN",
    "IDN",
    "KHM",
    "LAO",
    "MMR",
    "MYS",
    "PHL",
    "PNG",
    "SGP",
    "THA",
    "VNM"
  ],
  "NATO": [
    "ALB",
    "BEL",
    "BGR",
    "CAN",
    "CZE",
    "DEU",
    "DNK",
    "ESP",
    "EST",
    "FRA",
    "GBR",
    "GRC",
    "HRV",
    "HUN",
    "ISL",
    "ITA",
    "LTU",
    "LUX",
    "LVA",
    "MKD",
    "MNE",
    "NLD",
    "NOR",
    "POL",
    "PRT",
    "ROU",
    "SVK",
    "SVN",
    "TUR",
    "USA"
  ],
  "EU": [
    "AUT",
    "BEL",
    "BGR",
    "CYP",
    "CZE",
    "DEU",
    "DNK",
    "ESP",
    "EST",
    "FIN",
    "FRA",
    "GRC",
    "HRV",
    "HUN",
    "IRL",
    "ITA",
    "LTU",
    "LUX",
    "LVA",
    "MLT",
    "NLD",
    "POL",
    "PRT",
    "ROU",
    "SVK",
    "SVN",
    "SWE"
  ],
  "G20": [
    "ARG",
    "AUS",
    "BRA",
    "CAN",
    "CHN",
    "EUR",
    "DEU",
    "FRA",
    "GBR",
    "IDN",
    "IND",
    "ITA",
    "JPN",
    "KOR",
    "MEX",
    "RUS",
    "SAU",
    "TUR",
    "USA",
    "ZAF"
  ],
  "AU": [
    "AGO",
    "BDI",
    "BEN",
    "BFA",
    "BWA",
    "CAF",
    "CIV",
    "CMR",
    "COD",
    "COG",
    "COM",
    "CPV",
    "DJI",
    "DZA",
    "EGY",
    "ERI",
    "ETH",
    "GAB",
    "GHA",
    "GIN",
    "GMB",
    "GNB",
    "GNQ",
    "KEN",
    "LBR",
    "LBY",
    "LSO",
    "MAR",
    "MDG",
    "MLI",
    "MOZ",
    "MRT",
    "MUS",
    "MWI",
    "NAM",
    "NER",
    "NGA",
    "RWA",
    "ESH",
    "SDN",
    "SEN",
    "SLE",
    "SOM",
    "SSD",
    "STP",
    "SWZ",
    "SYC",
    "TCD",
    "TGO",
    "TUN",
    "TZA",
    "UGA",
    "ZAF",
    "ZMB",
    "ZWE"
  ],
  "AIPPM 1": [
    "AAP 0",
    "AAP 1",
    "ADS 0",
    "AIADMK 0",
    "AIMIM 0",
    "AITNC 0",
    "AITNC 1",
    "BBSS 0",
    "BJD 0",
    "BJP 0",
    "BJP 1",
    "BJP 10",
    "BJP 12",
    "BJP 13",
    "BJP 14",
    "BJP 15",
    "BJP 16",
    "BJP 17",
    "BJP 18",
    "BJP 2",
    "BJP 3",
    "BJP 4",
    "BJP 5",
    "BJP 6",
    "BJP 7",
    "BJP 8",
    "BJP 9",
    "BRS 0",
    "BSP 0",
    "CPI-M 0",
    "DMK 0",
    "INC 0",
    "INC 1",
    "INC 2",
    "INC 3",
    "INC 4",
    "INC 5",
    "INC 7",
    "INC 8",
    "INC 9",
    "JDU 0",
    "NCP 3",
    "NPP 0",
    "SAD 0",
    "SP 0",
    "YSRCP 0",
  ],
  "AIPPM 2": [
    "AAP 0",
    "AAP 1",
    "AAP 2",
    "AAP 3",
    "ADS 0",
    "AIADMK 0",
    "AIMIM 0",
    "AITNC 0",
    "AITNC 1",
    "AITNC 2",
    "BBSS 0",
    "BJD 0",
    "BJP 0",
    "BJP 1",
    "BJP 10",
    "BJP 12",
    "BJP 13",
    "BJP 14",
    "BJP 15",
    "BJP 16",
    "BJP 17",
    "BJP 18",
    "BJP 19",
    "BJP 2",
    "BJP 20",
    "BJP 21",
    "BJP 22",
    "BJP 23",
    "BJP 24",
    "BJP 25",
    "BJP 26",
    "BJP 27",
    "BJP 28",
    "BJP 29",
    "BJP 3",
    "BJP 30",
    "BJP 31",
    "BJP 32",
    "BJP 33",
    "BJP 34",
    "BJP 35",
    "BJP 36",
    "BJP 37",
    "BJP 38",
    "BJP 39",
    "BJP 4",
    "BJP 5",
    "BJP 6",
    "BJP 7",
    "BJP 8",
    "BJP 9",
    "BRS 0",
    "BSP 0",
    "CPI 0",
    "CPI-M 0",
    "CPI-M 1",
    "DMK 0",
    "DMK 1",
    "INC 0",
    "INC 1",
    "INC 10",
    "INC 11",
    "INC 12",
    "INC 13",
    "INC 14",
    "INC 15",
    "INC 16",
    "INC 17",
    "INC 18",
    "INC 19",
    "INC 2",
    "INC 3",
    "INC 4",
    "INC 5",
    "INC 7",
    "INC 8",
    "INC 9",
    "JDS 0",
    "JDU 0",
    "JMM 0",
    "MNF 0",
    "NCP 0",
    "NCP 1",
    "NCP 2",
    "NCP 3",
    "NCP 4",
    "NDPP 0",
    "NPP 0",
    "PDP 0",
    "RJD 0",
    "RJD 1",
    "RJD 2",
    "SAD 0",
    "SKM 0",
    "SP 0",
    "SS 0",
    "SS 1",
    "YSRCP 0",
  ],
};
