name: Build & Deploy to Firebase Hosting
"on":
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Config
        uses: subosito/flutter-action@v2
        with:
          channel: beta
  
      - name: Build
        run: |
          flutter config --enable-web
          cd "Source Code/website"
          flutter clean
          flutter pub get
          flutter build web --release
          cp -r assets/* build/web/assets/
  
      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entryPoint: "Source Code/website"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_ORATORZ37 }}"
          projectId: oratorz37
          channelId: live
    # steps:
    #   - uses: actions/checkout@v4
    #   - uses: actions/setup-node@v4
    #     with:
    #       node-version: 20
    #       cache: "npm"
    #       cache-dependency-path: "Source Code/react-website/package-lock.json"
    #   - run: npm ci
    #     working-directory: "Source Code/react-website"
    #   - run: npm run build
    #     working-directory: "Source Code/react-website"
    #   - uses: FirebaseExtended/action-hosting-deploy@v0
    #     with:
    #       entryPoint: "Source Code/react-website"
    #       repoToken: "${{ secrets.GITHUB_TOKEN }}"
    #       firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_ORATORZ37 }}"
    #       projectId: oratorz37
    #       channelId: live
    #     env:
    #       FIREBASE_CLI_EXPERIMENTS: webframeworks
